import { chromium } from '@playwright/test';
const OUT='/private/tmp/claude-501/-Users-nasrullahtanim-Downloads-SlideIn-Venture-slidein-venture/ac417f1e-93e3-41cc-93fd-b113e79acbe8/scratchpad/';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1440,height:1000}});
await p.goto('http://localhost:3111/steps',{waitUntil:'networkidle'});
await p.locator('#shape').scrollIntoViewIfNeeded();
await p.waitForTimeout(2500);
await p.locator('#shape').screenshot({path:OUT+'trackmap.png'});
await p.close();
const q=await b.newPage({viewport:{width:390,height:844}});
await q.goto('http://localhost:3111/steps',{waitUntil:'networkidle'});
await q.locator('#shape').scrollIntoViewIfNeeded();
await q.waitForTimeout(2500);
await q.locator('#shape').screenshot({path:OUT+'trackmap-mobile.png'});
await q.close();
await b.close();
