/**
 * BRAND — SlideIn Venture logo
 * ---------------------------------------------------------------------------
 * Single source for the mark. Colours resolve from theme tokens (--color-ink,
 * --color-brand) rather than raw hex, so a token change propagates here.
 *
 * Use --color-brand, NOT --color-primary: the `@theme inline` block at the
 * bottom of globals.css redefines --color-primary as var(--primary), which
 * resolves to near-black.
 *
 * The static favicon files (app/icon.svg, app/favicon.ico, app/apple-icon.png)
 * are generated by scripts/build-icons.mjs from logos/concepts/concept-3-icon.svg
 * and necessarily carry literal hex — a favicon has no CSS cascade to read from.
 * Re-run that script if the mark changes.
 */

import { cn } from '@/lib/utils';

/* ─── Icon mark — the two-tone S ──────────────────────────────────────────── */
export function LogoMark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="48 140 232 232"
      className={cn('shrink-0', className)}
      fill="none"
      strokeWidth={36}
      strokeLinecap="round"
      aria-hidden
      focusable="false"
    >
      <path
        stroke="var(--color-ink)"
        d="M224 198 C224 168 196 152 164 152 C130 152 104 172 104 200
           C104 230 132 246 164 252"
      />
      <path
        stroke="var(--color-brand)"
        d="M164 252 C198 258 224 274 224 302 C224 332 196 352 164 352
           C132 352 104 334 104 306"
      />
    </svg>
  );
}

/* ─── Wordmark — live text so it stays kernable and selectable ────────────── */
export function LogoWordmark({ className }: { className?: string }) {
  return (
    <span className={cn('inline-flex items-baseline gap-1.5', className)}>
      <span
        className="text-[20px] leading-none tracking-[-0.01em] text-[var(--color-ink)]"
        style={{ fontFamily: 'var(--font-display)' }}
      >
        SlideIn
      </span>
      <span className="text-[16px] font-medium leading-none tracking-tight text-[var(--color-brand)]">
        Venture
      </span>
    </span>
  );
}

/* ─── Full lockup ─────────────────────────────────────────────────────────── */
export function LogoLockup({
  className,
  markClassName,
}: {
  className?: string;
  markClassName?: string;
}) {
  return (
    <span className={cn('inline-flex items-center gap-2.5', className)}>
      <LogoMark className={cn('h-[22px] w-[22px]', markClassName)} />
      <LogoWordmark />
      <span className="sr-only">SlideIn Venture</span>
    </span>
  );
}
